### PR TITLE
Change kube module install to git clone

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by tchughesiv** [comment]
LGTM

**Comment by jcpowermac** [comment]
@l0rd or @tchughesiv ok to merge?

**Comment by l0rd** [comment]
@jcpowermac I didn't get the rationale behind this PR (why `git clone` instead of `ansible-galaxy install`?) but I don't know much about ansible (and even less about ansible galaxy) so that may be the reason :-)

Anyway LGTM too

**Comment by jcpowermac** [comment]
@l0rd it was the recommended fix by @tchughesiv it _should_ normally work but it also looks like those modules are deprecated.  I added an issue to eventually replace them.

**Pull request merged**
